## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file.
city_data_df = pd.read_csv("/Users/chrisgallegos/Programming/bootcamp/modules/6/module_challenge/Weather_Database/WeatherPy_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Castro,BR,-24.79,-50.01,60.96,94,100,10.87,light rain
1,1,Busselton,AU,-33.65,115.33,48.52,64,34,6.31,scattered clouds
2,2,Porto Novo,BJ,6.50,2.60,82.22,59,44,10.16,scattered clouds
3,3,Rikitea,PF,-23.12,-134.97,73.56,75,77,16.11,broken clouds
4,4,Letlhakane,BW,-21.42,25.58,74.43,19,2,6.22,clear sky

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 70

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
clean_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
clean_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Castro,BR,-24.79,-50.01,60.96,94,100,10.87,light rain
7,7,Port Alfred,ZA,-33.59,26.89,62.19,58,0,3.00,clear sky
11,11,Ust-Tsilma,RU,65.44,52.15,61.65,57,100,6.08,overcast clouds
12,12,Kruisfontein,ZA,-34.00,24.73,66.88,51,38,5.14,scattered clouds
18,18,Skibbereen,IE,51.55,-9.27,62.11,60,94,14.47,light rain
24,24,Oktyabrskiy,RU,54.48,53.47,65.43,59,8,7.00,clear sky
45,45,Rocha,UY,-34.48,-54.33,62.11,63,100,10.71,overcast clouds
54,54,Poum,NC,-20.23,164.02,65.35,74,100,7.09,overcast clouds
55,55,Avarua,CK,-21.21,-159.78,68.05,73,40,10.36,scattered clouds
66,66,Teahupoo,PF,-17.83,-149.27,64.36,78,98,3.76,overcast clouds

In [5]:
# 4a. Determine if there are any empty rows.
clean_df.count()

City_ID                103
City                   103
Country                103
Lat                    103
Lng                    103
Max Temp               103
Humidity               103
Cloudiness             103
Wind Speed             103
Current Description    103
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
# Filter the dataset to find the cities that fit the criteria and drop null values
clean_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)].dropna()

clean_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Castro,BR,-24.79,-50.01,60.96,94,100,10.87,light rain
7,7,Port Alfred,ZA,-33.59,26.89,62.19,58,0,3.00,clear sky
11,11,Ust-Tsilma,RU,65.44,52.15,61.65,57,100,6.08,overcast clouds
12,12,Kruisfontein,ZA,-34.00,24.73,66.88,51,38,5.14,scattered clouds
18,18,Skibbereen,IE,51.55,-9.27,62.11,60,94,14.47,light rain
24,24,Oktyabrskiy,RU,54.48,53.47,65.43,59,8,7.00,clear sky
45,45,Rocha,UY,-34.48,-54.33,62.11,63,100,10.71,overcast clouds
54,54,Poum,NC,-20.23,164.02,65.35,74,100,7.09,overcast clouds
55,55,Avarua,CK,-21.21,-159.78,68.05,73,40,10.36,scattered clouds
66,66,Teahupoo,PF,-17.83,-149.27,64.36,78,98,3.76,overcast clouds

In [7]:
# Determine if there are any empty rows.
clean_df.count()

City_ID                103
City                   103
Country                103
Lat                    103
Lng                    103
Max Temp               103
Humidity               103
Cloudiness             103
Wind Speed             103
Current Description    103
dtype: int64

In [8]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Castro,BR,60.96,light rain,-24.79,-50.01,
7,Port Alfred,ZA,62.19,clear sky,-33.59,26.89,
11,Ust-Tsilma,RU,61.65,overcast clouds,65.44,52.15,
12,Kruisfontein,ZA,66.88,scattered clouds,-34.00,24.73,
18,Skibbereen,IE,62.11,light rain,51.55,-9.27,
24,Oktyabrskiy,RU,65.43,clear sky,54.48,53.47,
45,Rocha,UY,62.11,overcast clouds,-34.48,-54.33,
54,Poum,NC,65.35,overcast clouds,-20.23,164.02,
55,Avarua,CK,68.05,scattered clouds,-21.21,-159.78,
66,Teahupoo,PF,64.36,overcast clouds,-17.83,-149.27,

In [9]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key, 
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
   
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]  
    
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [10]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df['Hotel Name'].replace('', np.nan, inplace=True)
clean_hotel_df = hotel_df.dropna()
clean_hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Castro,BR,60.96,light rain,-24.79,-50.01,CHACARA BAILLY
7,Port Alfred,ZA,62.19,clear sky,-33.59,26.89,The Halyards Hotel
11,Ust-Tsilma,RU,61.65,overcast clouds,65.44,52.15,U Praskov'i
12,Kruisfontein,ZA,66.88,scattered clouds,-34.00,24.73,Oyster Bay House Rental
18,Skibbereen,IE,62.11,light rain,51.55,-9.27,The West Cork Hotel
24,Oktyabrskiy,RU,65.43,clear sky,54.48,53.47,Гостиница Октябрьская
45,Rocha,UY,62.11,overcast clouds,-34.48,-54.33,Hotel Arrarte
55,Avarua,CK,68.05,scattered clouds,-21.21,-159.78,Paradise Inn
66,Teahupoo,PF,64.36,overcast clouds,-17.83,-149.27,Vanira Lodge
68,George,ZA,60.35,clear sky,-33.96,22.46,Protea Hotel by Marriott George King George

In [11]:
# 8a. Create the output File (CSV)
output_data_file = "/Users/chrisgallegos/Programming/bootcamp/modules/6/module_challenge/Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [32]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd><dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [33]:
# 11a. Add a marker layer for each city to the map. 

locations = clean_hotel_df[["Lat", "Lng"]]
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))